# --------------销售管理-客户管理--列表-----------
admin-api/mes/md/client/list:
  data:
  method: GET
  url: admin-api/mes/md/client/list?pageNum=1&pageSize=10


# --------------销售管理-客户管理--新增-----------
admin-api/mes/md/client:
  data: {"clientId": null, "clientCode": "C67634329", "clientName": "测试客户名称", "clientNick": null,
    "clientEn": null, "clientDes": null, "clientLogo": null, "clientType": null, "address": null,
    "website": null, "email": null, "tel": null, "contact1": null, "contact1Tel": null,
    "contact1Email": null, "contact2": null, "contact2Tel": null, "contact2Email": null,
    "creditCode": null, "enableFlag": "Y", "remark": null, "attr1": null, "attr2": null,
    "attr3": null, "attr4": null, "createBy": null, "createTime": null, "updateBy": null,
    "updateTime": null, "list": []}
  method: POST
  url: admin-api/mes/md/client


# --------------销售管理-客户管理--数据同步-----------
admin-api/open/O2/syncClientList:
  data:
  method: GET
  url: admin-api/open/O2/syncClientList