admin-api/plm/document:
  method: put
  name: 企业知识库-文档工作区-上传
  url: admin-api/plm/document
  data: {
    billType: "plm_document",
      itemTypeId: 12,
      documentType: "plm_document",
      id:,
      version:,
      documentList: [
        billType: "plm_document",
        documentType: "plm_document",
        documentVersionUid: "6bf1b40d-2d2b-4fdd-8dd6-0b476bea152e",
        fileName: "server",
        filePath: "开发",
        fileSuffix: "log",
        fileUuid: "b13cd446-d602-4a90-b869-c6bc146a9d10",
        itemTypeId: 12,
        originalFileName: "server.log",
        size: 5903,
        version: "3.0",
        versionUuid: "6bf1b40d-2d2b-4fdd-8dd6-0b476bea152e"
      ]
  }

admin-api/plm/document2:
  method: post
  name: 企业知识库-文档工作区-更新
  url: admin-api/plm/document
  data: {
    billType: "plm_document",
      createBy: "zxx",
      createTime: "2025-03-12 18:12:06",
      documentType: "plm_document",
      documentVersionUid: "58dbfe7b-8273-4e4e-b086-fbe6695984ed",
      fileName: "server22",
      filePath: "开发",
      fileSize: "5.76 K",
      fileSuffix: "log",
      fileUid: "648a1277-81f8-4312-9e6b-fb0b2cb79240",
      flowInsId:,
      flowKey:,
      iconPath:,
      id: 96,
      isCollect: "0",
      itemTypeCode: "",
      itemTypeId: 12,
      itemTypeName: "",
      originalFileName: "server.log",
      originalFilePath:,
      remark: "",
      size: 5903,
      status: "0",
      statusZH: "拟制",
      transceiverManagementId:,
      updateBy: "",
      updateTime:,
      version: "A.0.250312005",
  }

