admin-api/mes/plm/documentType:
  method: data
  name: 企业知识库-文档工作区-文档管理-新增
  url: admin-api/mes/plm/documentType
  data: {
    enableFlag: "Y",
      isExemptInspection: "Y",
      itemTypeName: "测试22222",
      orderNum: 1,
      parentTypeId: 1,
  }
