# --------------主数据--生产bom--新增-----------
admin-api/md/bom:
  data: {"itemId": 3730, "finishedRate": 100, "proRouteId": "", "proRouteName": "",
    "rootId": "", "lines": [{"itemId": 3732, "bomId": 869, "attritionRate": 0, "quantity": 1,
          "batchNumber": null}], "removeIds": []}
  method: POST
  name: 主数据--生产bom--新增
  url: admin-api/md/bom

# --------------主数据--生产bom--删除-----------
admin-api/md/bom/delete:
  data:
  method: DELETE
  name: 主数据--生产bom--删除
  url: admin-api/md/bom/0

# --------------主数据--生产bom--禁用-----------
admin-api/md/bom/enable:
  data:
    id: 0
    isEnable: false
  method: PUT
  name: 主数据--生产bom--禁用
  url: admin-api/md/bom/enable

# --------------主数据--生产bom--列表-----------
admin-api/md/bom/page:
  data:
  method: GET
  name: 主数据--生产bom--列表
  url: admin-api/md/bom/page?pageNum=1&pageSize=10&index=0&isEnable=&status=
