admin-api/plm/document/update/status:
  method: put
  name: 企业知识库-文档工作区-归档
  url: admin-api/plm/document/update/status
  data: {
    documentType: "plm_document",
    id: 96,
    operationType: "archived",
    status: "0",
  }

admin-api/plm/document/update/status2:
  method: put
  name: 企业知识库-文档工作区-取消归档
  url: admin-api/plm/document/update/status
  data: {
    documentType: "plm_document",
    id: 96,
    operationType: "unarchive",
    status: "0",
  }

admin-api/plm/document/update/status3:
  method: put
  name: 企业知识库-文档工作区-发布
  url: admin-api/plm/document/update/status
  data: {
    documentType: "plm_document",
    id: 96,
    operationType: "published",
    status: "0",
  }