admin-api/mes/wm/itemrecpt/detail:
  method: GET
  name: 采购管理--采购入库--采购入库明细--列表
  url: admin-api/mes/wm/itemrecpt/detail?pageNum=1&pageSize=10&beginRecptDate=2024-12-01&endRecptDate=2025-03-21
  data:
