# --------------项目管理--项目跟踪--列表-----------
admin-api/plm/v1/projectTask/list:
  data:
  method: GET
  url: admin-api/plm/v1/projectTask/list


# --------------项目管理--项目跟踪--查看-----------
admin-api/plm/v1/projectRole/list:
  data:
  method: GET
  url: admin-api/plm/v1/projectRole/list?projectId=97

# --------------项目管理--项目跟踪--查看--详情---------
admin-api/plm/v1/projectTask/detail:
  data:
  method: GET
  url: admin-api/plm/v1/projectTask/225

# --------------项目管理--项目跟踪--新增任务---------
admin-api/plm/v1/projectTask:
  data: {"taskNumber":"PLM202503250027","planDuration":2,"clientId":728,"clientName":"长发机械","milestone":"0","name":"测试","endTime":"2025-03-26","startTime":"2025-03-25","remark":"1","projectTemplateId":113,"roleUserIdListMap":[],"frontTaskIdList":null,"fileIdsList":[]}
  method: POST
  url: admin-api/plm/v1/projectTask