pre-url: http://192.168.3.89:20001/

admin-api/config.yml:
  method: json
  name: 登录
  url: admin-api/login
  headers:
    content-type: application/json;charset=UTF-8
  #这里按照这个格式可以输入不同的用户，供选择
  users:
    admin:
      username: "admin"
      password: "abc123456"
    user1:
      username: "alice"
      password: "alice_pwd"
    user2:
      username: "bob"
      password: "bob_pwd"
  mysql:
    host: 192.168.3.89
    port: 3306
    database: m1
    username: root
    password: abc123456
