# --------------项目管理--项目跟踪--新增--自动生成编号-----------
admin-api/system/autocode/get/V1_PROJECT_NUMBER:
  data:
  method: GET
  url: admin-api/system/autocode/get/V1_PROJECT_NUMBER

# --------------生产管理--基础信息-工序设置--新增--自动生成编号-----------
admin-api/system/autocode/get/PROCESS_CODE:
  data:
  method: GET
  url: admin-api/system/autocode/get/PROCESS_CODE

# --------------生产管理--基础信息-工艺流程--新增--自动生成编号-----------
admin-api/system/autocode/get/ROUTE_CODE:
  data:
  method: GET
  url: admin-api/system/autocode/get/ROUTE_CODE

# --------------生产管理--基础信息-工艺流程--新增--自动生成编号-----------
admin-api/system/autocode/get/MRP_CALCULATION_CODE:
  data:
  method: GET
  url: admin-api/system/autocode/get/MRP_CALCULATION_CODE

# --------------生产管理--生产工单--生产工单--新增--自动生成编号-----------
admin-api/system/autocode/get/WORKORDER_CODE:
  data:
  method: GET
  url: admin-api/system/autocode/get/WORKORDER_CODE