# --------------销售管理-销售订单-新增(sy)-----------
admin-api/mes/sm/sales:
  data:
    clientCode: "C00524"
    clientId: 1021
    clientName: "测试"
    currency: "美元"
    delivery: null
    salesCode: "SAL2025182"
    salesData: "2025-06-06 14:09:47"
    salesId: null
    salesName: null
    userId: 1
    userName: "admin"
    list:
      - searchValue: null
        createBy: null
        createTime: null
        remark: null
        areaCode: null
        areaId: null
        areaName: null
        batchManagement: true
        batchManagementZh: null
        clientItemCode: "是是是123低点"
        drawCode: null
        flowInsId: null
        flowKey: null
        index: 1
        inventoryCoefficient: 1
        inventoryUnit: "G"
        isEnable: true
        isEnableZh: null
        isExemptInspection: null
        isSafeStock: true
        isSafeStockZh: null
        isUse: null
        isUseZh: null
        itemCode: "JYXM202505280001"
        itemId: 3879
        itemName: "物料/产品名称70"
        itemNum: 2
        itemOrProduct: null
        itemTypeCode: "ITEM_TYPE_0149"
        itemTypeId: 318
        itemTypeName: "成品"
        locationCode: null
        locationId: null
        locationName: null
        packageName: "包装方式123"
        params: { }
        procureCoefficient: 1
        procureQuantityOnhand: 80
        procureUnit: "G"
        productionTemplateId: null
        productionTemplateName: null
        purchaseTemplateId: null
        purchaseTemplateName: null
        quantityOnhand: 80
        saleCoefficient: 1
        saleQuantityOnhand: 80
        saleUnit: "G"
        salesTemplateId: null
        salesTemplateName: null
        specification: "规格型号123"
        status: "0"
        statusZh: null
        supplyCoefficient: 1
        supplyQuantityOnhand: 80
        supplyUnit: "G"
        taxMoney: 4
        taxPrice: 2
        taxRate: 0
        totalMoney: 4
        unitMoney: 2
        unitOfMeasure: "G"
        unreceivedGoods: 2
        updateBy: null
        updateTime: null
        url: null
        version: null
        warehouseCode: "WH253"
        warehouseId: 369
        warehouseInfo:
          - 369
        warehouseName: "总仓库"
        warehouseNameZh: "总仓库"
  method: POST
  name: 销售管理-销售订单-新增
  url: admin-api/mes/sm/sales


# --------------销售管理-销售订单-列表--详情-----------
admin-api/mes/sm/sales/details:
  data:
  method: GET
  name: 销售管理-销售订单-列表--详情
  url: admin-api/mes/sm/sales/8

# --------------销售管理-销售订单-减单-----------
admin-api/mes/sm/salesLine/reduce:
  data: {"remark": "", "list": [{lineId: 8, number: 1}]}
  method: PUT
  name: 销售管理-销售订单-减单
  url: admin-api/mes/sm/salesLine/reduce

# --------------销售管理-销售订单-列表-----------
admin-api/mes/sm/sales/list:
  data:
  method: GET
  name: 销售管理-销售订单-列表
  url: admin-api/mes/sm/sales/list?pageNum=1&pageSize=10

# --------------销售管理-销售订单-删除-----------
admin-api/mes/sm/sales/delete:
  data:
  method: DELETE
  name: 销售管理-销售订单-删除
  url: admin-api/mes/sm/sales/8

# --------------销售管理-销售订单-撤销申请-----------
admin-api/oa/processInstance/cancleFlow:
  data: {"businessId": '8', "billType": "sm_sales"}
  method: POST
  name: 销售管理-销售订单-撤销申请
  url: admin-api/oa/processInstance/cancleFlow

# --------------销售管理-销售订单-流程信息-----------
admin-api/oa/flowImg/getDefImgByBusinessId:
  data: {"businessId": '8', "billType": "sm_sales"}
  method: POST
  name: 销售管理-销售订单-流程信息
  url: admin-api/oa/flowImg/getDefImgByBusinessId

# --------------销售管理-销售订单-流程信息-----------
admin-api/oa/myTask/getHisByBusinessId:
  data: {"businessId": '8', "billType": "sm_sales"}
  method: POST
  name: 销售管理-销售订单-流程信息
  url: admin-api/oa/myTask/getHisByBusinessId
