# --------------销售管理-销售退货--销售退货列表-----------
admin-api/mes/wm/rtsalse/list:
  data:
  method: GET
  url: admin-api/mes/wm/rtsalse/list?pageNum=1&pageSize=10


# --------------销售管理-销售退货--新增-----------
admin-api/mes/wm/rtsalse:
  data: {"salesId": 1016, "rtId": null, "rtCode": "PS41981360719", "rtName": null,
    "soCode": null, "clientName": "测试3/11客户", "clientCode": "C00513", "clientId": 727,
    "rtDate": "2025-03-22 17:48:42", "type": "04", "rtReason": null, "remark": "接口自动化备注",
    "list": [{"salesLineId": 1093, "salesId": 1016, "itemId": 3747, "itemCode": "IF20250319001",
          "itemName": "测试-领料", "itemNum": 100, "itemSpec": null, "specification": null,
          "packageName": null, "unitOfMeasure": "G", "matnr": null, "receivedGoods": 100,
          "unreceivedGoods": 0, "saleUnit": "G", "itemNumber": null, "saleCoefficient": 1,
          "goodsTime": null, "totalMoney": 200, "taxMoney": 200, "unitMoney": 2, "taxPrice": 2,
          "taxRate": 0, "saleQuantityOnhand": 0, "quantityOnhand": 0, "inventoryCoefficient": 1,
          "supplyCoefficient": 1, "supplyQuantityOnhand": 0, "batchManagement": false,
          "warehouseId": 351, "warehouseCode": "WH239", "warehouseName": "机加车间仓",
          "locationId": null, "locationCode": null, "locationName": null, "areaId": null,
          "areaCode": null, "areaName": null, "warehouseInfo": [351], "warehouseNameZh": "",
          "quantityRted": 1, "index": 1, "remark": "接口自动化原因"}], "userName": "admin",
    "userId": 1}
  method: POST
  url: admin-api/mes/wm/rtsalse


# --------------销售管理-销售退货--删除-----------
admin-api/mes/wm/rtsalse/delete:
  data:
  method: DELETE
  url: admin-api/mes/wm/rtsalse/5

# --------------销售管理-销售退货--详情-----------
admin-api/mes/wm/rtsalse/detail:
  data:
  method: GET
  url: admin-api/mes/wm/rtsalse/5
