# --------------生产管理--基础信息-工艺流程-列表-----------
admin-api/mes/pro/proroute/page:
  data:
  method: GET
  url: admin-api/mes/pro/proroute/page?pageNum=1&pageSize=10

# --------------生产管理--基础信息-工艺流程-新增-----------
admin-api/mes/pro/proroute:
  data: {"routeId": null, "routeCode": "R1435", "routeName": "接口自动化测试", "processList": [
       {"createBy": "admin", "createTime": "2025-02-19 13:45:02", "updateBy": null,
          "updateTime": "2025-02-19 13:45:01", "remark": null, "processId": 39, "processCode": "PROCESS1343",
          "processName": "小明测试工序", "defectCode": "DF009", "defectName": "666", "deptId": 103,
          "deptName": "工程部", "precautions": null, "proportion": 1, "workInstructionsName": null,
          "workInstructionsUrl": null, "inspectionStandardsName": null, "inspectionStandardsUrl": null,
          "workInstructionsList": [], "inspectionStandardsList": [], "workInstructions": "[{}]",
          "inspectionStandards": "[{}]", "submitAll": true, "submitDeptId": "", "submitUserId": "",
          "submitsZh": "所有人", "isInspected": "1", "templateId": null, "templateCode": null,
          "templateName": null, "routeType": 1, "id": null, "index": 1}], "productList": []}
  method: POST
  url: admin-api/mes/pro/proroute

# --------------生产管理--基础信息-工艺流程-详情-----------
admin-api/mes/pro/proroute/detail:
  data:
  method: GET
  url: admin-api/mes/pro/proroute/1


# --------------生产管理--基础信息-工艺流程-删除-----------
admin-api/mes/pro/proroute/delete:
  data:
  method: DELETE
  url: admin-api/mes/pro/proroute/1

# --------------生产管理--基础信息--产品工序信息--列表-----------
admin-api/mes/pro/proroute/selectProductProcess:
  data:
  method: GET
  url: admin-api/mes/pro/proroute/selectProductProcess?pageNum=1&pageSize=10
